---
name: Test Matrix Output

on:
  push:
    branches:
      - releases/**

permissions:
  contents: read
  id-token: write
  pull-requests: write


jobs:

  environment_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    env:
      repo: ${{ github.repository }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - id: set-matrix
        run: |
          set -eux
          echo "matrix=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${repo}/environments | jq -r '[ .environments[] | {environment: .name} ] | tojson' -)" >> $GITHUB_OUTPUT

  environment_exclude:
    needs: environment_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        include: ${{ fromJson(needs.environment_matrix.outputs.matrix) }}
    environment: ${{ matrix.environment }}
    outputs:
      matrix: ${{ steps.exclude-matrix.outputs.matrix }}
    steps:
      - id: exclude-matrix
        if: github.ref_name != vars.release
        run: |
          set -eux
          echo "matrix=$(echo "${{ matrix.environment }}" | jq -Rr '[ {environment: .}] | tojson' -)" >> $GITHUB_OUTPUT


  run_workflow:
    needs:
      - environment_matrix
      - environment_exclude
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.environment_matrix.outputs.matrix) }}
        # exclude: ${{fromJson(needs.environment_exclude.outputs.matrix) }}
    environment: ${{ matrix.environment }}
    steps:
      - name: Run Workflow
        run: |
          set -eux
          echo "${{ fromJson(needs.environment_exclude.outputs.matrix) }}"
          echo "Running workflow for ${{ matrix.environment }}" >> $GITHUB_OUTPUT

...