---
name: Test Matrix Output

on:
  push:
    branches:
      - releases/**

permissions:
  contents: read
  id-token: write
  pull-requests: write


jobs:

  create_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    env:
      owner: ${{ github.repository_owner }}
      repo: ${{ github.repository }}
      release: ${{ github.ref_name }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - id: set-matrix
        run: |
          json=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${repo}/environments | jq -r '{include: [ .environments[] | {environment: .name} ]} | tojson' -)
          echo "::set-output name=matrix::${json}"

  work_with_matrix:
    needs: create_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.create_matrix.outputs.matrix) }}
    environment: ${{ matrix.environment }}
    steps:
      - run: echo ENVIRONMENT ${{ matrix.environment }}
      - run: echo CIDR_BLOCK ${{ vars.TF_VAR_cidr_block }}
      - run: echo RELEASE ${{ vars.RELEASE }}
      - run: echo REF_NAME ${{ github.ref_name}}
      - run: echo REF_TYPE ${{ github.ref_type}}

...