---
name: Test Matrix Output

on:
  push:
    branches:
      - releases/**

permissions:
  contents: read
  id-token: write
  pull-requests: write


jobs:

  build_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    env:
      repo: ${{ github.repository }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - id: set-matrix
        run: |
          set -eux
          echo "matrix=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${repo}/environments | jq -r '[ .environments[] | {environment: .name} ] | tojson' -)" >> $GITHUB_OUTPUT

  matrix_exclude:
    needs: build_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        include: ${{ fromJson(needs.build_matrix.outputs.matrix) }}
    environment: ${{ matrix.environment }}
    steps:
      - id: exclude-matrix
        uses: cloudposse/github-action-matrix-outputs-write@v1
        if: github.ref_name != vars.release
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.environment }}
          outputs: |-
            exclude: true

  filtered_matrix:
    needs: matrix_exclude
    runs-on: ubuntu-latest
    steps:
      - id: read
        uses: cloudposse/github-action-matrix-outputs-read@v1
        with:
          matrix-step-name: matrix_exclude
      - id: print
        run: |
          set -eux
          echo "${{ fromJson(steps.read.outputs.result) }}" | jq '[.exclude | keys[] | {environment: .}] | tojson'
    outputs:
      result: "${{ fromJson(steps.read.outputs.result) }}"

  run_workflow:
    needs: filtered_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.environment_matrix.outputs.matrix) }}
        exlude: ${{ fromJson(needs.filtered_matrix.outputs.result) }}
    environment: ${{ matrix.environment }}
    steps:
      - name: Run Workflow
        run: |
          set -eux
          echo "${{ fromJson(needs.environment_exclude.outputs.matrix) }}"
          echo "Running workflow for ${{ matrix.environment }}" >> $GITHUB_OUTPUT

...