---
name: Test Matrix Output

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  create_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "::set-output name=matrix::{\"include\":[{\"environment\":\"prod-use1\",\"release\":\"1.0\"},{\"environment\":\"prod-usw1\",\"release\":\"1.0\"},{\"environment\":\"prod-usc1\",\"release\":\"1.1\"}]}"
  work_with_matrix:
    needs: create_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.create_matrix.outputs.matrix) }}
    environment: ${{ matrix.environment }}
    if: github.ref == "refs/tags/v${{ vars.release }}.*"
    steps:
      - run: echo ENVIRONMENT ${{ matrix.environment }}
      - run: echo CIDR_BLOCK ${{ vars.TF_VAR_cidr_block }}
      - run: echo RELEASE ${{ vars.release }}
      - run: echo REF ${{ github.ref}}

...