---
name: Test Matrix Output

on:
  workflow_dispatch:

jobs:
  create_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "::set-output name=matrix::{\"include\":[{\"environment\":\"prod-use1\",\"release\":\"1.0\"},{\"environment\":\"prod-usw1\",\"release\":\"1.0\"}]}"
  work_with_matrix:
    needs: create_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.create_matrix.outputs.matrix)}}
    steps:
      - run: echo ${{ matrix.environment }}
      - run: echo ${{ matrix.release }}
...