---
name: Test Matrix Output

on:
  push:
    branches:
      - releases/**

permissions:
  contents: read
  id-token: write
  pull-requests: write


jobs:

  build_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    env:
      repo: ${{ github.repository }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - id: set-matrix
        run: |
          set -eux
          echo "matrix=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${repo}/environments | jq -r '[ .environments[] | {environment: .name} ] | tojson' -)" >> $GITHUB_OUTPUT

  matrix_exclude:
    needs: build_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        include: ${{ fromJson(needs.build_matrix.outputs.matrix) }}
    environment: ${{ matrix.environment }}
    steps:
      - id: exclude-file
        if: github.ref_name != vars.release
        run: |
          set -eux
          echo "{\"environment\":\"${{ matrix.environment }}\"}" > exclude-file
      - id: upload-artifact
        uses: actions/upload-artifact@v2
        if: github.ref_name != vars.release
        with:
          name: $(echo "{\"environment\":\"${{ matrix.environment }}\"}" | sha256sum | awk '{print $1}')
          path: exclude-file

  filtered_matrix:
    needs: matrix_exclude
    runs-on: ubuntu-latest
    steps:
      - id: download-artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - id: print
        run: |
          set -eux
          ls -l

  # run_workflow:
  #   needs: filtered_matrix
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       include: ${{ fromJson(needs.environment_matrix.outputs.matrix) }}
  #       exlude: ${{ fromJson(needs.filtered_matrix.outputs.result) }}
  #   environment: ${{ matrix.environment }}
  #   steps:
  #     - name: Run Workflow
  #       run: |
  #         set -eux
  #         echo "${{ fromJson(needs.environment_exclude.outputs.matrix) }}"
  #         echo "Running workflow for ${{ matrix.environment }}" >> $GITHUB_OUTPUT

...