---
name: Test Matrix Output

on:
  push:
    branches:
      - releases/**

permissions:
  contents: read
  id-token: write
  pull-requests: write


jobs:

  create_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    env:
      owner: ${{ github.repository_owner }}
      repo: ${{ github.repository }}
      release: ${{ github.ref_name }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - id: set-matrix
        run: |
          echo "matrix=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${repo}/environments | jq -r '{include: [ .environments[] | {environment: .name} ]} | tojson' -)" >> $GITHUB_OUTPUT

  get_release:
    needs: create_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.create_matrix.outputs.matrix) }}
    environment: ${{ matrix.environment }}
    outputs:
      release: ${{ vars.release }}

  run_workflow:
    needs:
      - create_matrix
      - get_release
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.create_matrix.outputs.matrix) }}
    environment: ${{ matrix.environment }}
    if: github.ref_name == needs.get_release.outputs.release

...